### ISSUE TITLE
Schematics can't be deleted

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/Arkitektonika#45]
https://api.schematic.cloud/delete/5595823a929f69d5c6b298dae3fb8e34 expects a GET, but should be DELETE.

**Comment by NotMyFault** [comment]
I just assigned you, so we don't lose track of the issue.

**Comment by PierreSchwang** [comment]
It... is a DELETE? And was forever https://github.com/IntellectualSites/Arkitektonika/blob/7924d0f48741058b4ba16849204de88030aef47c/app/routes/delete.js#L40

**Comment by NotMyFault** [comment]
> It... is a DELETE? And was forever
> 
> https://github.com/IntellectualSites/Arkitektonika/blob/7924d0f48741058b4ba16849204de88030aef47c/app/routes/delete.js#L40

See the discord discussion for context. I don't remember all details, but I do verify it doesn't work.

**Comment by PierreSchwang** [comment]
To have a status update in this issue:
> I think the issue is we're mixing backend urls with frontend urls?
like for deletion, the player should get an url for the frontend where they can press a button to delete the schematic
(https://discord.com/channels/268444645527126017/1005569224598618163/1019678570538356788)

**Comment by PierreSchwang** [comment]
Closing, as the API works as expected.
